// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHB4rDDZKyCZbdBYfO-pie8UDj8VnUS-M',
    appId: '1:851894655407:web:3ae7d6386ac81672bf775a',
    messagingSenderId: '851894655407',
    projectId: 'comiksan-24bd2',
    authDomain: 'comiksan-24bd2.firebaseapp.com',
    storageBucket: 'comiksan-24bd2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwEPm6kdbHekDCu8AUL9NIURbipOeGYyU',
    appId: '1:851894655407:android:81d46b5786d4d481bf775a',
    messagingSenderId: '851894655407',
    projectId: 'comiksan-24bd2',
    storageBucket: 'comiksan-24bd2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAeIN5Jcf_yfyi2e7wexKfX9pXBJnfytc',
    appId: '1:851894655407:ios:8ea945bfa4edb88bbf775a',
    messagingSenderId: '851894655407',
    projectId: 'comiksan-24bd2',
    storageBucket: 'comiksan-24bd2.firebasestorage.app',
    iosBundleId: 'com.example.comiksan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAeIN5Jcf_yfyi2e7wexKfX9pXBJnfytc',
    appId: '1:851894655407:ios:8ea945bfa4edb88bbf775a',
    messagingSenderId: '851894655407',
    projectId: 'comiksan-24bd2',
    storageBucket: 'comiksan-24bd2.firebasestorage.app',
    iosBundleId: 'com.example.comiksan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBHB4rDDZKyCZbdBYfO-pie8UDj8VnUS-M',
    appId: '1:851894655407:web:f0d44c35162ef2bdbf775a',
    messagingSenderId: '851894655407',
    projectId: 'comiksan-24bd2',
    authDomain: 'comiksan-24bd2.firebaseapp.com',
    storageBucket: 'comiksan-24bd2.firebasestorage.app',
  );
}
